let bookSeeds = [
	{
		bookId: 1,
		title: "Drinking At The Shadows",
		author: "Jane R. Pacheco",
		genre: "Fantasy",
		yearWritten: 1951,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1420.12
	},
	{
		bookId: 2,
		title: "Hurt By History",
		author: "Stewart N. Shaffer",
		genre: "Fantasy",
		yearWritten: 1921,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 291.66
	},
	{
		bookId: 3,
		title: "Hurt By History",
		author: "Morgan Emerson",
		genre: "Fantasy",
		yearWritten: 1993,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 951.35
	},
	{
		bookId: 4,
		title: "Smiles In The Mountains",
		author: "Sandra Beasley",
		genre: "Fantasy",
		yearWritten: 2002,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1464.30
	},
	{
		bookId: 5,
		title: "Reach Of The Sea",
		author: "Roanna W. Wynn",
		genre: "Mystery,",
		yearWritten: 1943,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 96.99
	},
	{
		bookId: 6,
		title: "The Letters of Saint Cuthbert",
		author: "Eugenia L. Jordan",
		genre: "Mystery,",
		yearWritten: 1992,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 329.51
	},
	{
		bookId: 7,
		title: "Reach Of The Ashes",
		author: "Rahim Simmons",
		genre: "Mystery,",
		yearWritten: 2000,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 349.28
	},
	{
		bookId: 8,
		title: "Shelter In The Swamp",
		author: "Holmes Briggs",
		genre: "Non-fiction,",
		yearWritten: 1950,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 895.83
	},
	{
		bookId: 9,
		title: "Lush Life",
		author: "Ivy Dickson",
		genre: "Poetry,",
		yearWritten: 1972,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 886.85
	},
	{
		bookId: 10,
		title: "Battle Of Myself",
		author: "Keegan Gallagher",
		genre: "Fantasy",
		yearWritten: 1950,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1183.75
	},
	{
		bookId: 11,
		title: "Confessions Of My Destiny",
		author: "Brielle M. Glover",
		genre: "Fantasy",
		yearWritten: 1991,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 909.28
	},
	{
		bookId: 12,
		title: "Belonging To A Storm",
		author: "Keith Elliott",
		genre: "Western,",
		yearWritten: 1966,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1023.37
	},
	{
		bookId: 13,
		title: "Dear Charles",
		author: "Alexander Bullock",
		genre: "Non-fiction,",
		yearWritten: 1955,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 896.70
	},
	{
		bookId: 14,
		title: "Vanish At The Commander",
		author: "Clio Young",
		genre: "SciFi,",
		yearWritten: 1902,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 880.39
	},
	{
		bookId: 15,
		title: "Kicking Dreams",
		author: "Shoshana D. Hurst",
		genre: "Western,",
		yearWritten: 1925,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 981.40
	},
	{
		bookId: 16,
		title: "Fade Into The World",
		author: "Brenda Mcfarland",
		genre: "Western,",
		yearWritten: 1925,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1079.61
	},
	{
		bookId: 17,
		title: "On Raising Goats",
		author: "Garrison Hooper",
		genre: "Mystery,",
		yearWritten: 2010,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1335.13
	},
	{
		bookId: 18,
		"Author": "Gregory Richards",
		"author": "Edan Stone",
		"genre": "Poetry,",
		"yearWritten": 1972,
		"edition": "1st",
		"binding": "Hardcover",
		"condition": "Fine",
		"price":"1433.06
	},
	{
		bookId: 19,
		title: "The Forging of Wrathgor",
		author: "Cynthia Mcmahon",
		genre: "Non-fiction,",
		yearWritten: 1950,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 846.67
	},
	{
		bookId: 20,
		title: "Wild Heart",
		author: "Kiayada Matthews",
		genre: "Mystery,",
		yearWritten: 1980,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 254.60
	},
	{
		bookId: 21,
		title: "Lake of the Lily",
		author: "Briar L. Contreras",
		genre: "SciFi,",
		yearWritten: 1969,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 500.70
	},
	{
		bookId: 22,
		title: "Mental",
		author: "Charles K. Sharpe",
		genre: "Mystery,",
		yearWritten: 1961,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 693.59
	},
	{
		bookId: 23,
		title: "Unconventional Risk",
		author: "India Q. Duncan",
		genre: "Mystery,",
		yearWritten: 1913,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 288.56
	},
	{
		bookId: 24,
		title: "The Rock in the Frost",
		author: "Hedy N. Haley",
		genre: "SciFi,",
		yearWritten: 1919,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1029.19
	},
	{
		bookId: 25,
		title: "Mistress Pat: A Novel of Silver Bush.",
        author: "L.M. Montgomery",
        genre: "Fiction",
        yearWritten: 1925,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1476.05
	},
	{
		bookId: 26,
		title: "Harry the Fox",
		author: "Florence H. Turner",
		genre: "Mystery,",
		yearWritten: 1955,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 349.36
	},
	{
		bookId: 27,
		title: "The Healing Company",
		author: "Victor L. Sloan",
		genre: "Non-fiction,",
		yearWritten: 1980,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1316.52
	},
	{
		bookId: 28,
		title: "The Physician's Bodyguard",
		author: "Amethyst L. Dominguez",
		genre: "Mystery,",
		yearWritten: 1923,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1421.78
	},
	{
		bookId: 29,
		title: "A History of Armageddon",
		author: "Robert P. Rose",
		genre: "SciFi,",
		yearWritten: 2020,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 969.64
	},
	{
		bookId: 30,
		title: "The Ashes of Francesca",
		author: "Samuel B. Austin",
		genre: "Mystery,",
		yearWritten: 1987,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1190.96
	},
	{
		bookId: 31,
		title: "Burning The Breeze",
		author: "Nasim Conrad",
		genre: "Mystery,",
		yearWritten: 1916,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 676.79
	},
	{
		bookId: 32,
		title: "The Songbird's Bridal",
		author: "Brenna Davidson",
		genre: "Fantasy",
		yearWritten: 2013,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1153.18
	},
	{
		bookId: 33,
		title: "The Enchanted Ones",
		author: "Merrill V. Crane",
		genre: "Thriller,",
		yearWritten: 1982,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 855.06
	},
	{
		bookId: 34,
		title: "The Earthsea Quartet",
        author: "Ursula K. Le Guin",
        genre: "Fantasy",
        yearWritten: 2019,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 853.27
	},
	{
		bookId: 35,
		title: "Novel Blessings",
		author: "Matthew Mcdonald",
		genre: "Mystery,",
		yearWritten: 1902,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 930.47
	},
	{
		bookId: 36,
		title: "April's Code",
		author: "Geraldine V. Hester",
		genre: "Poetry,",
		yearWritten: 1931,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1425.69
	},
	{
		bookId: 37,
		title: "The Split Queen",
		author: "Buffy Harrison",
		genre: "Mystery,",
		yearWritten: 1964,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1117.59
	},
	{
		bookId: 38,
		title: "Scars of Sand",
		author: "Roth F. Vasquez",
		genre: "Western,",
		yearWritten: 2002,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 787.26
	},
	{
		bookId: 39,
		title: "The Death of the Reef",
		author: "Joseph G. Whitfield",
		genre: "Western,",
		yearWritten: 1982,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 63.47
	},
	{
		bookId: 40,
		title: "A Certain Eye",
		author: "Hedley Stevens",
		genre: "Non-fiction,",
		yearWritten: 1923,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1211.55
	},
	{
		bookId: 41,
		title: "The Dandelion Chronicles",
		author: "Brooke G. Pennington",
		genre: "Non-fiction,",
		yearWritten: 1948,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1365.16
	},
	{
		bookId: 42,
		title: "Horse With No Rider",
		author: "Hope V. Higgins",
		genre: "Non-fiction,",
		yearWritten: 2014,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 344.69
	},
	{
		bookId: 43,
		title: "Questions of Belief",
		author: "Abel X. Savage",
		genre: "Western,",
		yearWritten: 2018,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1423.84
	},
	{
		bookId: 44,
		title: "Cavanaugh's Movie",
		author: "Halee House",
		genre: "SciFi,",
		yearWritten: 2018,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 202.65
	},
	{
		bookId: 45,
		title: "The Face of the Revolution",
		author: "Jordan A. Camacho",
		genre: "Non-fiction,",
		yearWritten: 1934,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1465.26
	},
	{
		bookId: 46,
		title: "Andree de Taverney or The Downfall of French Monarchy",
        author: "Alexander Dumas",
        genre: "Fiction",
        yearWritten: 1896,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 104.55
	},
	{
		bookId: 47,
		title: "Cavanaugh's Movie",
		author: "Dorian I. Decker",
		genre: "SciFi,",
		yearWritten: 1906,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 446.01
	},
	{
		bookId: 48,
		title: "Plain Burdens",
		author: "Dieter S. Nielsen",
		genre: "Mystery,",
		yearWritten: 2011,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1169.58
	},
	{
		bookId: 49,
		title: "Gold in the Afterglow",
		author: "Abdul O'connor",
		genre: "Western,",
		yearWritten: 1936,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1498.88
	},
	{
		bookId: 50,
		title: "Twilight's Chance",
		author: "Brenda D. Craft",
		genre: "Fantasy",
		yearWritten: 1909,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1343.81
	},
	{
		bookId: 51,
		title: "Boys in Crime",
		author: "Lavinia O. Chambers",
		genre: "Mystery,",
		yearWritten: 1942,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 303.91
	},
	{
		bookId: 52,
		title: "Secret of the Year",
		author: "Skyler K. Booker",
		genre: "Western,",
		yearWritten: 1924,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 634.37
	},
	{
		bookId: 53,
		title: "South Waiting",
		author: "Nathaniel H. Love",
		genre: "SciFi,",
		yearWritten: 1917,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 196.55
	},
	{
		bookId: 54,
		title: "Swimming With Sharks",
		author: "Imelda Patrick",
		genre: "Mystery,",
		yearWritten: 1957,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 995.61
	},
	{
		bookId: 55,
		title: "Coffin's Breed",
		author: "Dennis O. Dillon",
		genre: "Mystery,",
		yearWritten: 2014,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1465.67
	},
	{
		bookId: 56,
		title: "Seduction Sinister",
		author: "Jada Bell",
		genre: "Poetry,",
		yearWritten: 1910,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 100.64
	},
	{
		bookId: 57,
		title: "The Curve of the Thing",
		author: "Doris X. Green",
		genre: "Poetry,",
		yearWritten: 1966,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1366.45
	},
	{
		bookId: 58,
		title: "The Strange Key",
		author: "Laurel Benson",
		genre: "Mystery,",
		yearWritten: 1995,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 207.90
	},
	{
		bookId: 59,
		title: "The Roar of the Trail",
		author: "Hayfa Parsons",
		genre: "Mystery,",
		yearWritten: 1932,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1347.21
	},
	{
		bookId: 60,
		title: "Horse With No Rider",
		author: "Dora G. Donovan",
		genre: "SciFi,",
		yearWritten: 1897,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 143.68
	},
	{
		bookId: 61,
		title: "Mandy and the Leviathan",
		author: "Winter Hunt",
		genre: "Mystery,",
		yearWritten: 2017,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 198.45
	},
	{
		bookId: 62,
		title: "The Anatomy of Deceit",
		author: "Dexter Z. Keller",
		genre: "Fantasy",
		yearWritten: 1976,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 332.88
	},
	{
		bookId: 63,
		title: "The Saxon's Storm",
		author: "August B. Hutchinson",
		genre: "Mystery,",
		yearWritten: 1963,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 954.78
	},
	{
		bookId: 64,
		title: "A Singular Fate",
		author: "Coby Simpson",
		genre: "Mystery,",
		yearWritten: 1928,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1340.49
	},
	{
		bookId: 65,
		title: "Hard Gun",
		author: "Gannon J. Fischer",
		genre: "Thriller,",
		yearWritten: 1976,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 835.02
	},
	{
		bookId: 66,
		title: "Circles of Joy",
		author: "Suki Farrell",
		genre: "Fantasy",
		yearWritten: 1967,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 838.59
	},
	{
		bookId: 67,
		title: "Borders of Blood",
		author: "Briar Barnett",
		genre: "Mystery,",
		yearWritten: 2010,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 843.37
	},
	{
		bookId: 68,
		title: "Death of the Horned Baobab",
		author: "Ulric Weeks",
		genre: "Mystery,",
		yearWritten: 2012,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 464.87
	},
	{
		bookId: 69,
		title: "City of Glass",
		author: "Merrill Cooper",
		genre: "Non-fiction,",
		yearWritten: 2012,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1118.39
	},
	{
		bookId: 70,
		title: "Black Lace",
		author: "Nathaniel Z. Bowman",
		genre: "SciFi,",
		yearWritten: 1984,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 990.87
	},
	{
		bookId: 71,
		title: "The Merry Wives of Windsor",
        author: "William Shakespeare",
        genre: "Thriller",
        yearWritten: 1939,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 177.19
	},
	{
		bookId: 72,
		title: "FantasyWorld",
		author: "Julian G. Rogers",
		genre: "Non-fiction,",
		yearWritten: 1939,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1475.37
	},
	{
		bookId: 73,
		title: "the Ancient Stone",
		author: "Keelie O'connor",
		genre: "Western,",
		yearWritten: 1899,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 987.23
	},
	{
		bookId: 74,
		title: "Bunny Farm",
		author: "Minerva C. Dawson",
		genre: "Western,",
		yearWritten: 1987,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 974.95
	},
	{
		bookId: 75,
		title: "Northanger Abbey",
        author: "Jane Austin",
        genre: "Thriller",
        yearWritten: 1939,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 847.07
	},
	{
		bookId: 76,
		title: "Zenith of Mars",
		author: "Charlotte X. Reynolds",
		genre: "Poetry,",
		yearWritten: 1907,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1493.39
	},
	{
		bookId: 77,
		title: "Love Eternal",
		author: "Willow Holloway",
		genre: "Mystery,",
		yearWritten: 1901,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 59.71
	},
	{
		bookId: 78,
		title: "Lonestar Chain",
		author: "Adara Grimes",
		genre: "Western,",
		yearWritten: 1954,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 919.28
	},
	{
		bookId: 79,
		title: "Horses of Wood",
		author: "Emery V. Wolf",
		genre: "Fantasy",
		yearWritten: 1960,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1047.11
	},
	{
		bookId: 80,
		title: "The Corpse in the Grave",
		author: "Aaron Sullivan",
		genre: "SciFi,",
		yearWritten: 1908,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1457.34
	},
	{
		bookId: 81,
		title: "Tree Of Life",
		author: "Olga Luna",
		genre: "SciFi,",
		yearWritten: 2017,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1291.01
	},
	{
		bookId: 82,
		title: "Stay Hidden",
		author: "Lydia T. Mueller",
		genre: "SciFi,",
		yearWritten: 1953,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1392.88
	},
	{
		bookId: 83,
		title: "Sirius Sinking",
		author: "Zorita Y. Macias",
		genre: "Thriller,",
		yearWritten: 2015,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1147.70
	},
	{
		bookId: 84,
		title: "Cats of the World",
		author: "Chloe Coffey",
		genre: "Mystery,",
		yearWritten: 1978,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1009.59
	},
	{
		bookId: 85,
		title: "Dark Dream",
		author: "Bruno C. Suarez",
		genre: "Western,",
		yearWritten: 1938,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1136.08
	},
	{
		bookId: 86,
		title: "Our Insolvency",
		author: "Gay C. Collier",
		genre: "SciFi,",
		yearWritten: 1972,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1448.01
	},
	{
		bookId: 87,
		title: "Wanted for Crimes",
		author: "Eugenia R. Chavez",
		genre: "Thriller,",
		yearWritten: 1950,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1327.33
	},
	{
		bookId: 88,
		title: "Steel Grace",
		author: "Porter Golden",
		genre: "Thriller,",
		yearWritten: 1902,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 603.18
	},
	{
		bookId: 89,
		title: "Made in Texas",
		author: "Tamara Moreno",
		genre: "Non-fiction,",
		yearWritten: 1972,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1014.42
	},
	{
		bookId: 90,
		title: "My Notes from the Sea: Inroads of the Outback",
		author: "Kirby G. Velez",
		genre: "Poetry,",
		yearWritten: 1994,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1103.28
	},
	{
		bookId: 91,
		title: "Confused By Electricity",
		author: "Lareina I. Fry",
		genre: "SciFi,",
		yearWritten: 1931,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 749.15
	},
	{
		bookId: 92,
		title: "2619: Alpha",
		author: "Patrick Vinson",
		genre: "Thriller,",
		yearWritten: 2015,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1411.76
	},
	{
		bookId: 93,
		title: "Understanding",
		author: "Iola E. Sargent",
		genre: "Mystery,",
		yearWritten: 2007,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 100.52
	},
	{
		bookId: 94,
		title: "Falling Fallen",
		author: "Hedy Michael",
		genre: "Western,",
		yearWritten: 1916,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 709.80
	},
	{
		bookId: 95,
		title: "Maid in Leather",
		author: "Brent Rivers",
		genre: "Thriller,",
		yearWritten: 2002,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 882.02
	},
	{
		bookId: 96,
		title: "The Fractured Earth",
		author: "Hilel L. Hebert",
		genre: "Mystery,",
		yearWritten: 1969,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 908.58
	},
	{
		bookId: 97,
		title: "Who's Afraid of Virginia Woolf?",
        author: "Edward Albee",
        genre: "Thriller",
        yearWritten: "1964",
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 52.72
	},
	{
		bookId: 98,
		title: "In the Forest",
		author: "Hamilton Shields",
		genre: "Western,",
		yearWritten: 1948,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 931.69
	},
	{
		bookId: 99,
		title: "The Ghostly Cottage",
		author: "Julie Leon",
		genre: "Poetry,",
		yearWritten: 1989,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 815.17
	},
	{
		bookId: 100,
		title: "The Missing Staircase",
		author: "Wing Singleton",
		genre: "Fantasy",
		yearWritten: 1941,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 419.89
	},
	{
		bookId: 101,
		title: "Cold Hand",
		author: "Kitra O. Mckinney",
		genre: "Non-fiction,",
		yearWritten: 2004,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 639.93
	},
	{
		bookId: 102,
		title: "Creatures Of The Planet",
		author: "Hayden Kim",
		genre: "Fantasy",
		yearWritten: 1921,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1210.90
	},
	{
		bookId: 103,
		title: "Shot of Fury",
		author: "Chandler B. Hays",
		genre: "SciFi,",
		yearWritten: 1922,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 355.68
	},
	{
		bookId: 104,
		title: "The Stranger",
		author: "Jena V. Aguirre",
		genre: "Non-fiction,",
		yearWritten: 1979,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 221.24
	},
	{
		bookId: 105,
		title: "The Book of Uncommon Law",
		author: "Nyssa F. Ellison",
		genre: "Thriller,",
		yearWritten: 1961,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1133.94
	},
	{
		bookId: 106,
		title: "Monstrous Philosophies",
		author: "Kirestin Randolph",
		genre: "Poetry,",
		yearWritten: 2001,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1080.25
	},
	{
		bookId: 107,
		title: "85 Poems. London, Hutchinson, 1993.",
        author: "Gavin Ewart",
        genre: "Poetry",
        yearWritten: 1993,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 383.81
	},
	{
		bookId: 108,
		title: " Because the Night",
        author: "James Ellroy",
        genre: "Mystery",
        yearWritten: 1987,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 535.91
	}

]

export default bookSeeds;