let bookSeeds = [
	{
		id: 1,
		title: "Drinking At The Shadows",
		author: "Jane R. Pacheco",
		genre: "Fantasy",
		yearPublished: 1951,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1420.12
	},
	{
		id: 2,
		title: "Hurt By History",
		author: "Stewart N. Shaffer",
		genre: "Fantasy",
		yearPublished: 1921,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 291.66
	},
	{
		id: 3,
		title: "Hurt By History",
		author: "Morgan Emerson",
		genre: "Fantasy",
		yearPublished: 1993,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 951.35
	},
	{
		id: 4,
		title: "Smiles In The Mountains",
		author: "Sandra Beasley",
		genre: "Fantasy",
		yearPublished: 2002,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1464.30
	},
	{
		id: 5,
		title: "Reach Of The Sea",
		author: "Roanna W. Wynn",
		genre: "Mystery,",
		yearPublished: 1943,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 96.99
	},
	{
		id: 6,
		title: "The Letters of Saint Cuthbert",
		author: "Eugenia L. Jordan",
		genre: "Mystery,",
		yearPublished: 1992,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 329.51
	},
	{
		id: 7,
		title: "Reach Of The Ashes",
		author: "Rahim Simmons",
		genre: "Mystery,",
		yearPublished: 2000,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 349.28
	},
	{
		id: 8,
		title: "Shelter In The Swamp",
		author: "Holmes Briggs",
		genre: "Non-fiction,",
		yearPublished: 1950,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 895.83
	},
	{
		id: 9,
		title: "Lush Life",
		author: "Ivy Dickson",
		genre: "Poetry,",
		yearPublished: 1972,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 886.85
	},
	{
		id: 10,
		title: "Battle Of Myself",
		author: "Keegan Gallagher",
		genre: "Fantasy",
		yearPublished: 1950,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1183.75
	},
	{
		id: 11,
		title: "Confessions Of My Destiny",
		author: "Brielle M. Glover",
		genre: "Fantasy",
		yearPublished: 1991,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 909.28
	},
	{
		id: 12,
		title: "Belonging To A Storm",
		author: "Keith Elliott",
		genre: "Western,",
		yearPublished: 1966,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1023.37
	},
	{
		id: 13,
		title: "Dear Charles",
		author: "Alexander Bullock",
		genre: "Non-fiction,",
		yearPublished: 1955,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 896.70
	},
	{
		id: 14,
		title: "Vanish At The Commander",
		author: "Clio Young",
		genre: "SciFi,",
		yearPublished: 1902,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 880.39
	},
	{
		id: 15,
		title: "Kicking Dreams",
		author: "Shoshana D. Hurst",
		genre: "Western,",
		yearPublished: 1925,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 981.40
	},
	{
		id: 16,
		title: "Fade Into The World",
		author: "Brenda Mcfarland",
		genre: "Western,",
		yearPublished: 1925,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1079.61
	},
	{
		id: 17,
		title: "On Raising Goats",
		author: "Garrison Hooper",
		genre: "Mystery,",
		yearPublished: 2010,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1335.13
	},
	{
		id: 18,
		"Author": "Gregory Richards",
		"author": "Edan Stone",
		"genre": "Poetry,",
		"yearPublished": 1972,
		"edition": "1st",
		"binding": "Hardcover",
		"condition": "Fine",
		"price":"1433.06
	},
	{
		id: 19,
		title: "The Forging of Wrathgor",
		author: "Cynthia Mcmahon",
		genre: "Non-fiction,",
		yearPublished: 1950,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 846.67
	},
	{
		id: 20,
		title: "Wild Heart",
		author: "Kiayada Matthews",
		genre: "Mystery,",
		yearPublished: 1980,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 254.60
	},
	{
		id: 21,
		title: "Lake of the Lily",
		author: "Briar L. Contreras",
		genre: "SciFi,",
		yearPublished: 1969,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 500.70
	},
	{
		id: 22,
		title: "Mental",
		author: "Charles K. Sharpe",
		genre: "Mystery,",
		yearPublished: 1961,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 693.59
	},
	{
		id: 23,
		title: "Unconventional Risk",
		author: "India Q. Duncan",
		genre: "Mystery,",
		yearPublished: 1913,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 288.56
	},
	{
		id: 24,
		title: "The Rock in the Frost",
		author: "Hedy N. Haley",
		genre: "SciFi,",
		yearPublished: 1919,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1029.19
	},
	{
		id: 25,
		title: "Mistress Pat: A Novel of Silver Bush.",
        author: "L.M. Montgomery",
        genre: "Fiction",
        yearPublished: 1925,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1476.05
	},
	{
		id: 26,
		title: "Harry the Fox",
		author: "Florence H. Turner",
		genre: "Mystery,",
		yearPublished: 1955,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 349.36
	},
	{
		id: 27,
		title: "The Healing Company",
		author: "Victor L. Sloan",
		genre: "Non-fiction,",
		yearPublished: 1980,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1316.52
	},
	{
		id: 28,
		title: "The Physician's Bodyguard",
		author: "Amethyst L. Dominguez",
		genre: "Mystery,",
		yearPublished: 1923,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1421.78
	},
	{
		id: 29,
		title: "A History of Armageddon",
		author: "Robert P. Rose",
		genre: "SciFi,",
		yearPublished: 2020,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 969.64
	},
	{
		id: 30,
		title: "The Ashes of Francesca",
		author: "Samuel B. Austin",
		genre: "Mystery,",
		yearPublished: 1987,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1190.96
	},
	{
		id: 31,
		title: "Burning The Breeze",
		author: "Nasim Conrad",
		genre: "Mystery,",
		yearPublished: 1916,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 676.79
	},
	{
		id: 32,
		title: "The Songbird's Bridal",
		author: "Brenna Davidson",
		genre: "Fantasy",
		yearPublished: 2013,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1153.18
	},
	{
		id: 33,
		title: "The Enchanted Ones",
		author: "Merrill V. Crane",
		genre: "Thriller,",
		yearPublished: 1982,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 855.06
	},
	{
		id: 34,
		title: "The Earthsea Quartet",
        author: "Ursula K. Le Guin",
        genre: "Fantasy",
        yearPublished: 2019,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 853.27
	},
	{
		id: 35,
		title: "Novel Blessings",
		author: "Matthew Mcdonald",
		genre: "Mystery,",
		yearPublished: 1902,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 930.47
	},
	{
		id: 36,
		title: "April's Code",
		author: "Geraldine V. Hester",
		genre: "Poetry,",
		yearPublished: 1931,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1425.69
	},
	{
		id: 37,
		title: "The Split Queen",
		author: "Buffy Harrison",
		genre: "Mystery,",
		yearPublished: 1964,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1117.59
	},
	{
		id: 38,
		title: "Scars of Sand",
		author: "Roth F. Vasquez",
		genre: "Western,",
		yearPublished: 2002,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 787.26
	},
	{
		id: 39,
		title: "The Death of the Reef",
		author: "Joseph G. Whitfield",
		genre: "Western,",
		yearPublished: 1982,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 63.47
	},
	{
		id: 40,
		title: "A Certain Eye",
		author: "Hedley Stevens",
		genre: "Non-fiction,",
		yearPublished: 1923,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1211.55
	},
	{
		id: 41,
		title: "The Dandelion Chronicles",
		author: "Brooke G. Pennington",
		genre: "Non-fiction,",
		yearPublished: 1948,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1365.16
	},
	{
		id: 42,
		title: "Horse With No Rider",
		author: "Hope V. Higgins",
		genre: "Non-fiction,",
		yearPublished: 2014,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 344.69
	},
	{
		id: 43,
		title: "Questions of Belief",
		author: "Abel X. Savage",
		genre: "Western,",
		yearPublished: 2018,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1423.84
	},
	{
		id: 44,
		title: "Cavanaugh's Movie",
		author: "Halee House",
		genre: "SciFi,",
		yearPublished: 2018,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 202.65
	},
	{
		id: 45,
		title: "The Face of the Revolution",
		author: "Jordan A. Camacho",
		genre: "Non-fiction,",
		yearPublished: 1934,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1465.26
	},
	{
		id: 46,
		title: "Andree de Taverney or The Downfall of French Monarchy",
        author: "Alexander Dumas",
        genre: "Fiction",
        yearPublished: 1896,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 104.55
	},
	{
		id: 47,
		title: "Cavanaugh's Movie",
		author: "Dorian I. Decker",
		genre: "SciFi,",
		yearPublished: 1906,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 446.01
	},
	{
		id: 48,
		title: "Plain Burdens",
		author: "Dieter S. Nielsen",
		genre: "Mystery,",
		yearPublished: 2011,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1169.58
	},
	{
		id: 49,
		title: "Gold in the Afterglow",
		author: "Abdul O'connor",
		genre: "Western,",
		yearPublished: 1936,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1498.88
	},
	{
		id: 50,
		title: "Twilight's Chance",
		author: "Brenda D. Craft",
		genre: "Fantasy",
		yearPublished: 1909,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1343.81
	},
	{
		id: 51,
		title: "Boys in Crime",
		author: "Lavinia O. Chambers",
		genre: "Mystery,",
		yearPublished: 1942,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 303.91
	},
	{
		id: 52,
		title: "Secret of the Year",
		author: "Skyler K. Booker",
		genre: "Western,",
		yearPublished: 1924,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 634.37
	},
	{
		id: 53,
		title: "South Waiting",
		author: "Nathaniel H. Love",
		genre: "SciFi,",
		yearPublished: 1917,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 196.55
	},
	{
		id: 54,
		title: "Swimming With Sharks",
		author: "Imelda Patrick",
		genre: "Mystery,",
		yearPublished: 1957,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 995.61
	},
	{
		id: 55,
		title: "Coffin's Breed",
		author: "Dennis O. Dillon",
		genre: "Mystery,",
		yearPublished: 2014,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1465.67
	},
	{
		id: 56,
		title: "Seduction Sinister",
		author: "Jada Bell",
		genre: "Poetry,",
		yearPublished: 1910,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 100.64
	},
	{
		id: 57,
		title: "The Curve of the Thing",
		author: "Doris X. Green",
		genre: "Poetry,",
		yearPublished: 1966,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1366.45
	},
	{
		id: 58,
		title: "The Strange Key",
		author: "Laurel Benson",
		genre: "Mystery,",
		yearPublished: 1995,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 207.90
	},
	{
		id: 59,
		title: "The Roar of the Trail",
		author: "Hayfa Parsons",
		genre: "Mystery,",
		yearPublished: 1932,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1347.21
	},
	{
		id: 60,
		title: "Horse With No Rider",
		author: "Dora G. Donovan",
		genre: "SciFi,",
		yearPublished: 1897,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 143.68
	},
	{
		id: 61,
		title: "Mandy and the Leviathan",
		author: "Winter Hunt",
		genre: "Mystery,",
		yearPublished: 2017,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 198.45
	},
	{
		id: 62,
		title: "The Anatomy of Deceit",
		author: "Dexter Z. Keller",
		genre: "Fantasy",
		yearPublished: 1976,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 332.88
	},
	{
		id: 63,
		title: "The Saxon's Storm",
		author: "August B. Hutchinson",
		genre: "Mystery,",
		yearPublished: 1963,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 954.78
	},
	{
		id: 64,
		title: "A Singular Fate",
		author: "Coby Simpson",
		genre: "Mystery,",
		yearPublished: 1928,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1340.49
	},
	{
		id: 65,
		title: "Hard Gun",
		author: "Gannon J. Fischer",
		genre: "Thriller,",
		yearPublished: 1976,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 835.02
	},
	{
		id: 66,
		title: "Circles of Joy",
		author: "Suki Farrell",
		genre: "Fantasy",
		yearPublished: 1967,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 838.59
	},
	{
		id: 67,
		title: "Borders of Blood",
		author: "Briar Barnett",
		genre: "Mystery,",
		yearPublished: 2010,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 843.37
	},
	{
		id: 68,
		title: "Death of the Horned Baobab",
		author: "Ulric Weeks",
		genre: "Mystery,",
		yearPublished: 2012,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 464.87
	},
	{
		id: 69,
		title: "City of Glass",
		author: "Merrill Cooper",
		genre: "Non-fiction,",
		yearPublished: 2012,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1118.39
	},
	{
		id: 70,
		title: "Black Lace",
		author: "Nathaniel Z. Bowman",
		genre: "SciFi,",
		yearPublished: 1984,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 990.87
	},
	{
		id: 71,
		title: "The Merry Wives of Windsor",
        author: "William Shakespeare",
        genre: "Thriller",
        yearPublished: 1939,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 177.19
	},
	{
		id: 72,
		title: "FantasyWorld",
		author: "Julian G. Rogers",
		genre: "Non-fiction,",
		yearPublished: 1939,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1475.37
	},
	{
		id: 73,
		title: "the Ancient Stone",
		author: "Keelie O'connor",
		genre: "Western,",
		yearPublished: 1899,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 987.23
	},
	{
		id: 74,
		title: "Bunny Farm",
		author: "Minerva C. Dawson",
		genre: "Western,",
		yearPublished: 1987,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 974.95
	},
	{
		id: 75,
		title: "Northanger Abbey",
        author: "Jane Austin",
        genre: "Thriller",
        yearPublished: 1939,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 847.07
	},
	{
		id: 76,
		title: "Zenith of Mars",
		author: "Charlotte X. Reynolds",
		genre: "Poetry,",
		yearPublished: 1907,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1493.39
	},
	{
		id: 77,
		title: "Love Eternal",
		author: "Willow Holloway",
		genre: "Mystery,",
		yearPublished: 1901,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 59.71
	},
	{
		id: 78,
		title: "Lonestar Chain",
		author: "Adara Grimes",
		genre: "Western,",
		yearPublished: 1954,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 919.28
	},
	{
		id: 79,
		title: "Horses of Wood",
		author: "Emery V. Wolf",
		genre: "Fantasy",
		yearPublished: 1960,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1047.11
	},
	{
		id: 80,
		title: "The Corpse in the Grave",
		author: "Aaron Sullivan",
		genre: "SciFi,",
		yearPublished: 1908,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1457.34
	},
	{
		id: 81,
		title: "Tree Of Life",
		author: "Olga Luna",
		genre: "SciFi,",
		yearPublished: 2017,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1291.01
	},
	{
		id: 82,
		title: "Stay Hidden",
		author: "Lydia T. Mueller",
		genre: "SciFi,",
		yearPublished: 1953,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1392.88
	},
	{
		id: 83,
		title: "Sirius Sinking",
		author: "Zorita Y. Macias",
		genre: "Thriller,",
		yearPublished: 2015,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 1147.70
	},
	{
		id: 84,
		title: "Cats of the World",
		author: "Chloe Coffey",
		genre: "Mystery,",
		yearPublished: 1978,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 1009.59
	},
	{
		id: 85,
		title: "Dark Dream",
		author: "Bruno C. Suarez",
		genre: "Western,",
		yearPublished: 1938,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1136.08
	},
	{
		id: 86,
		title: "Our Insolvency",
		author: "Gay C. Collier",
		genre: "SciFi,",
		yearPublished: 1972,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1448.01
	},
	{
		id: 87,
		title: "Wanted for Crimes",
		author: "Eugenia R. Chavez",
		genre: "Thriller,",
		yearPublished: 1950,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1327.33
	},
	{
		id: 88,
		title: "Steel Grace",
		author: "Porter Golden",
		genre: "Thriller,",
		yearPublished: 1902,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 603.18
	},
	{
		id: 89,
		title: "Made in Texas",
		author: "Tamara Moreno",
		genre: "Non-fiction,",
		yearPublished: 1972,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1014.42
	},
	{
		id: 90,
		title: "My Notes from the Sea: Inroads of the Outback",
		author: "Kirby G. Velez",
		genre: "Poetry,",
		yearPublished: 1994,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1103.28
	},
	{
		id: 91,
		title: "Confused By Electricity",
		author: "Lareina I. Fry",
		genre: "SciFi,",
		yearPublished: 1931,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 749.15
	},
	{
		id: 92,
		title: "2619: Alpha",
		author: "Patrick Vinson",
		genre: "Thriller,",
		yearPublished: 2015,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1411.76
	},
	{
		id: 93,
		title: "Understanding",
		author: "Iola E. Sargent",
		genre: "Mystery,",
		yearPublished: 2007,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 100.52
	},
	{
		id: 94,
		title: "Falling Fallen",
		author: "Hedy Michael",
		genre: "Western,",
		yearPublished: 1916,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 709.80
	},
	{
		id: 95,
		title: "Maid in Leather",
		author: "Brent Rivers",
		genre: "Thriller,",
		yearPublished: 2002,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 882.02
	},
	{
		id: 96,
		title: "The Fractured Earth",
		author: "Hilel L. Hebert",
		genre: "Mystery,",
		yearPublished: 1969,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 908.58
	},
	{
		id: 97,
		title: "Who's Afraid of Virginia Woolf?",
        author: "Edward Albee",
        genre: "Thriller",
        yearPublished: "1964",
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 52.72
	},
	{
		id: 98,
		title: "In the Forest",
		author: "Hamilton Shields",
		genre: "Western,",
		yearPublished: 1948,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 931.69
	},
	{
		id: 99,
		title: "The Ghostly Cottage",
		author: "Julie Leon",
		genre: "Poetry,",
		yearPublished: 1989,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 815.17
	},
	{
		id: 100,
		title: "The Missing Staircase",
		author: "Wing Singleton",
		genre: "Fantasy",
		yearPublished: 1941,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 419.89
	},
	{
		id: 101,
		title: "Cold Hand",
		author: "Kitra O. Mckinney",
		genre: "Non-fiction,",
		yearPublished: 2004,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 639.93
	},
	{
		id: 102,
		title: "Creatures Of The Planet",
		author: "Hayden Kim",
		genre: "Fantasy",
		yearPublished: 1921,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1210.90
	},
	{
		id: 103,
		title: "Shot of Fury",
		author: "Chandler B. Hays",
		genre: "SciFi,",
		yearPublished: 1922,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 355.68
	},
	{
		id: 104,
		title: "The Stranger",
		author: "Jena V. Aguirre",
		genre: "Non-fiction,",
		yearPublished: 1979,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 221.24
	},
	{
		id: 105,
		title: "The Book of Uncommon Law",
		author: "Nyssa F. Ellison",
		genre: "Thriller,",
		yearPublished: 1961,
		edition: "1st",
		binding: "Hardcover",
		condition: "Very Good",
		price: 1133.94
	},
	{
		id: 106,
		title: "Monstrous Philosophies",
		author: "Kirestin Randolph",
		genre: "Poetry,",
		yearPublished: 2001,
		edition: "1st",
		binding: "Hardcover",
		condition: "Good",
		price: 1080.25
	},
	{
		id: 107,
		title: "85 Poems. London, Hutchinson, 1993.",
        author: "Gavin Ewart",
        genre: "Poetry",
        yearPublished: 1993,
		edition: "1st",
		binding: "Hardcover",
		condition: "Near Fine",
		price: 383.81
	},
	{
		id: 108,
		title: " Because the Night",
        author: "James Ellroy",
        genre: "Mystery",
        yearPublished: 1987,
		edition: "1st",
		binding: "Hardcover",
		condition: "Fine",
		price: 535.91
	}

]

export default bookSeeds;